### ISSUE TITLE
Usage of authorized_scope returns an immutable scope (using method where! raise ActiveRecord:: ImmutableRelation)

### ISSUE THREAD

**Issue by 0legovich** [palkan/action_policy#101] opened 2020-01-17 22:57 UTC
### Tell us about your environment

Ruby 2.5.1
Rails 5.1.6.2
Action Policy 0.4.3

### What did you do?
I added the ActionPolicy gem to my project. In `index` action of my controller I used methods: `where!` and `order!`.
 
### What did you expect to happen?
When I use `authorized_scope(User.all)` with the method `where!` I expect it to change my scope.

### What actually happened?
If I use `authorized_scope(User.all)` with `where!`, I get the exception: `ActiveRecord:: ImmutableRelation`. 

Can I get immutable relation after using `authorized_scope(User.all)`?
I have to used method `clone` in my Policy like this: `relation_scope { |relation| relation.where('id > 0').clone }` to resolve this problem.
I think more correctly to use method `clone` here: https://github.com/palkan/action_policy/blob/master/lib/action_policy/authorizer.rb#L33

Thank you.

**Comment by 0legovich** [comment] 2020-01-18 23:01
# Steps to reproduce

or see [this commit diff](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35)

1. `rails _5.1.6.2_ new -d postgresql --api -J -T ap_relation_scope --skip-yarn --skip-active-storage --skip-sprockets --skip-coffee --skip-javascript -v`
2. `cd ap_relation_scope`
3. `bundle exeс rails g model User`
4. `bundle exeс rails db:create db:migrate`
5. [Add](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R44) action_policy in gem file
6. `bundle install`
7. `bundle exeс rails g action_policy:install`
8. `bundle exeс rails g action_policy:policy User` + [edit](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-9b967b022bf519b15da6d2f86f2b4794)
9. `bundle exeс rails g controller Users index authorized_index` + [edit](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-4e05ad0d64e6100656b63ad1e78f32c5)
10. [Edit](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-4e05ad0d64e6100656b63ad1e78f32c5) ApplicationController
11. [Edit](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-21497849d8f00507c9c8dcaf6288b136) routes.rb
12. [Add](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R31)`factory_bot_rails` and `rspec-rails` in Gemfile
13. `bundle install`
14. `bundle exec rails g rspec:install`
15. [Add](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-e3f619f247130354a105db1f482f5d1d) factory User
16. `bundle exec rails g rspec:controller Users index authorized_index` + [edit](https://github.com/0legovich/ap_relation_scope/commit/c3e963c7ab0b8a86919a4a2eabe90bd2c0286f35#diff-289c53b4c0f454861db9a893a5ceb957R14)
17. `bundle exec rspec`

**Comment by palkan** [comment] 2020-01-20 16:21
Thanks for the reproduction!

Did I understood you correctly: the problems is that `authorized_scope` + `where!` raises ImmutableRelation, right?

**Comment by palkan** [comment] 2020-01-20 18:00
I found the reason: `ActiveRecord::Relation#respond_to_missing?`

```ruby
def respond_to_missing?(method, include_private = false)
  super || @klass.respond_to?(method, include_private) ||
  # this line initialize the arel, which makes the relation immutable
  arel.respond_to?(method, include_private)
end

def assert_mutability!
  raise ImmutableRelation if @loaded
  raise ImmutableRelation if defined?(@arel) && @arel
end
```

`respond_to_missing?` is called when we're looking up a policy class for the relation (`policy_class` method triggers it).

Fixed in https://github.com/palkan/action_policy/commit/38ea2852d7f67c572cf0136c34845e420caf0c24.

**Closed** 2020-01-20 17:59 UTC
Labels: investigate

**Comment by 0legovich** [comment] 2020-01-20 22:00
Thank you very much for a quick fix!
