### ISSUE TITLE
Support only/except options for additional context authorizations

### ISSUE THREAD

**Issue by jonathankau** [palkan/action_policy#80] opened 2019-09-25 00:33 UTC
The explicit context feature (https://actionpolicy.evilmartians.io/#/authorization_context?id=explicit-context) is useful for passing in additional context params that determine the result of a Policy rule.

```ruby
class FooPolicy < ApplicationPolicy
  authorize :another_param, allow_nil: true

  def route_one?
    another_param == 'bar'
  end

  def route_two?
    true
  end
end
```

However, I am finding that the default `ApplicationPolicy#authorize` definition is a bit too restrictive. If I have some routes that need the additional contexts, but some don't, then I need to pass `nil` in in order to avoid the `ActionPolicy::AuthorizationContextMissing` error.

Am I missing something regarding how to implement this? It would be great if we could define something like `authorize :another_context, except: route_two?`.

**Comment by palkan** [comment] 2019-09-25 11:17
Hey!

> I have some routes that need the additional contexts

Do you have these routes defined in the same controller or you have actions with different contexts within the same controller?

We assume that the authorization context is the same at least within the same controller and propose the following schema for dynamic contexts:

```ruby
# policy has nillable contexts
class FooPolicy < ApplicationPolicy
  authorize :user # included by default in Rails
  authorize :bar, allow_nil: true
end

# base controller defines only required contexts
class ApplicationController < ActionController::Base
  authorize :user, through: :current_user # included by default in Rails
end

# a particular controller defines optional contexts
class BarsController < ApplicationController
  authorize :bar, through: :current_bar
end
```

Speaking about adding an additional context to a particular route without explicitly defining it in `authorize!` call (is that what you meant, right?), you can do the following hack:

```ruby
before_action only: :some_action do
  @__authorization_context = {user: user, bar: @bar}
end
```

That's an internal API  though (thus could change in the future). We should consider adding a similar public API as soon as we figure out all the possible cases.

**Comment by jonathankau** [comment] 2019-09-25 20:37
Thanks for the quick reply. Is there a reason why the authorization context is presumed to be the same within a controller?

For this specific example, I want to pass a controller param as an additional context for some routes. This param isn't relevant to all of the routes within the controller.

**Comment by palkan** [comment] 2019-09-26 09:28
> Is there a reason why the authorization context is presumed to be the same within a controller?

Controller is an example of _authorization behaviour_, which defines the context. So, it's by design.

The problem here is that Rails controller could have multiple responsibilities (although that's probably a good sign to split it in two).

I think, having `:only` / `:except` could be a way out.

**Comment by palkan** [comment] 2019-12-12 02:24
Optional authorization context support has been added in https://github.com/palkan/action_policy/pull/95 which helps to resolve the original issue. Closing this for now.

**Closed by palkan** 2019-12-12 02:24 UTC
