### ISSUE TITLE
`NoMethodError` when using `allowed_to?` and `alias_rule`

### ISSUE THREAD

**Issue by krisleech** [palkan/action_policy#125] opened 2020-07-24 11:20 UTC
When one policy calls another using `allowed_to?` and the rule is aliased we get a `NoMethodError` for the rule.

If we use Ruby's `alias` or `alias_method`, instead of `alias_rule`, this does not happen. What we loose by using `alias` in all places instead of `alias_rule`, caching?

Reading https://github.com/palkan/action_policy/issues/79 and https://github.com/palkan/action_policy/issues/34 I couldn't tell if this is a bug or intended.

Many thanks!

Here is a reproduction of the problem:

```ruby
require "bundler/inline"

gemfile(false) do
  source "https://rubygems.org"
  gem "rspec"
  gem "action_policy"
  gem "pry-byebug"
end

require "action_policy"

require 'rspec/autorun'

puts ActionPolicy::VERSION

class Policy1 < ActionPolicy::Base
  def update?
    allowed_to?(:update?, record, with: Policy2)
  end
end

class Policy2 < ActionPolicy::Base
  def manage?
    true
  end

  alias_rule :update?, to: :manage?
end

class Controller
  include ActionPolicy::Behaviour

  authorize :user

  attr_reader :user

  def initialize(user)
    @user = user
  end

  def call(record)
    authorize!(record, to: :update?, with: Policy1)
  end
end

RSpec.describe 'allowed_to? calling aliased rule' do
  it 'causes an error' do
    user = Object.new
    record = Object.new
    controller = Controller.new(user)

    expect { controller.call(record) }.not_to raise_error
   
  end
end
```

The exception raised is: `expected no Exception, got #<NoMethodError: undefined method `update?' for #<Policy2`

### Tell us about your environment

**Action Policy Version:** 0.4.4

**Comment by palkan** [comment] 2020-07-24 11:35
> if this is a bug or intended.

That's an intended behaviour.

> What we loose by using alias in all places instead of alias_rule, caching?

Yep, caching, first; rules bloat—second; also, testing.

The idea of `alias_rule` is to be something like syntax sugar for the outer abstraction layers (those, using policies).
When you're within the _policies layer_, we assume that it is known which rules are defined in policies, there is no need for aliases.

Given that this question arises from time to time, adding aliases support to `allowed_to?` within policies makes sense.

That's covered in #79, so, closing this one.

**Closed by palkan** 2020-07-24 11:35 UTC

**Comment by krisleech** [comment] 2020-07-24 15:15
Thank-you for taking the time to respond, especially so quickly, much appreciated.
