### ISSUE TITLE
Authorizing method access

### ISSUE THREAD

**Issue by lifeiscontent** [palkan/action_policy#93] opened 2019-11-15 02:07 UTC
Hey there,

in GraphQL there's a way to do field level authorization, is it possible to do the same with action_policy?

e.g.

if I have model `Post` that has a `description`, `title` and `is_draft`

I want to say `title` is accessible to everyone and `description` is only accessible if the `post` is not a draft

how would you do this in the policy?

**Comment by palkan** [comment] 2019-11-15 16:07
Hey!

Using [action_policy-graphql](https://github.com/palkan/action_policy-graphql) you can do something like:

```ruby
module Types
  class Post < Base
    # ...
    field :description, String,  authorize: { to: :show_description? }
  end
end

class PostPolicy < ApplicationPolicy 
  def show_description?
    !draft?
  end
end
```

This code would raise `ActionPolicy::Unauthorized` when `description` is a part of the selection.

Or you can make this field return `nil` if the policy check returns `false`:

```ruby
field :description, String,  authorize: { to: :show_description?, raise: false }
```

**Comment by lifeiscontent** [comment] 2019-11-15 18:26
@palkan thank you! this makes sense to me. And thank you for writing such a nice gem 👍

**Comment by lifeiscontent** [comment] 2019-11-15 18:28
@palkan not sure if this is a feature, but generally you would only `raise` if it's a mutation and if it's a query, return `nil`. is this a feature ActionPolicy supports? or could we make it work via a config exposed in an initializer?

**Comment by palkan** [comment] 2019-11-15 18:47
There is currently no such global configuration parameter but, I think, we can add it.

Could you open an issue in `action_policy-graphql` describing this feature request (ideally, with code examples) or PR with the tests for the expected behavior?

**Comment by palkan** [comment] 2019-11-25 19:09
Closed in favor of https://github.com/palkan/action_policy-graphql/issues/14

**Closed by palkan** 2019-11-25 19:09 UTC

**Comment by mfrost** [comment] 2020-01-14 01:22
@palkan hate to post on a closed issue, but I am stumped by the example you've given. If I am reading the [field extension](https://github.com/palkan/action_policy-graphql/blob/v0.3.0/lib/action_policy/graphql/authorized_field.rb#L30) correctly, the value given to `#allowed_to?` is the actual string description in your example. When I do something similar, I am getting policy lookup exceptions since it is not getting the `Post`, but a string.

Have I misunderstood how to authorize a field?

**Comment by palkan** [comment] 2020-01-14 01:28
> Have I misunderstood how to authorize a field?

You're right. The example isn't correct; the correct way would be the following:

```ruby
field :description, String, null: false

def description
  authorize! object, to: :show_description?
  object.description
end
```

So, to make it work as you expect we need to add an option to specify the parent as the authorization target, smth like:

```ruby
field :description, String,  authorize: {to: :show_description?, parent: true}

# or using a separate option
field :description, String, authorize_field: true # use show_<field_name>? by default
```

Would you like to create an issue or PR in `action_policy-graphql`?

**Comment by mfrost** [comment] 2020-01-14 01:30
@palkan wow, thanks for such a quick reply! Wish I had asked sooner. I can certainly take a look at adding that to the other library. Thank you for the wonderful gems.
