### ISSUE TITLE
uninitialized constant ActionController::Parameters

### ISSUE THREAD

**Issue by rainerborene** [palkan/action_policy#235] opened 2023-02-19 04:36 UTC
This only happens when running a production Sidekiq server.

/bundle/ruby/3.2.0/gems/action_policy-0.6.5/lib/action_policy/rails/scope_matchers/action_controller_params.rb:16:in `<top (required)>': uninitialized constant ActionController::Parameters (NameError)

> ActionPolicy::Base.scope_matcher :action_controller_params, ActionController::Parameters
>                                                                             ^^^^^^^^^^^^
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/action_policy-0.6.5/lib/action_policy/railtie.rb:8:in `<module:ActionPolicy>'
>         from /bundle/ruby/3.2.0/gems/action_policy-0.6.5/lib/action_policy/railtie.rb:3:in `<top (required)>'
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/action_policy-0.6.5/lib/action_policy.rb:47:in `<module:ActionPolicy>'
>         from /bundle/ruby/3.2.0/gems/action_policy-0.6.5/lib/action_policy.rb:12:in `<top (required)>'
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/runtime.rb:55:in `each'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/runtime.rb:55:in `block in require'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/runtime.rb:44:in `each'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/runtime.rb:44:in `require'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler.rb:195:in `require'
>         from /bundle/ruby/3.2.0/gems/sidekiq-ent-7.0.4/bin/sidekiqswarm:40:in `<top (required)>'
>         from /bundle/ruby/3.2.0/bin/sidekiqswarm:25:in `load'
>         from /bundle/ruby/3.2.0/bin/sidekiqswarm:25:in `<top (required)>'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
>         from /bundle/ruby/3.2.0/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
>         from /usr/lib/fullstaq-ruby/versions/3.2.0-jemalloc/bin/bundle:25:in `load'
>         from /usr/lib/fullstaq-ruby/versions/3.2.0-jemalloc/bin/bundle:25:in `<main>'
>

**Comment by palkan** [comment] 2023-02-23 03:11
Thanks for reporting!

Looks like the same regression as reported in #228 (still haven't had time to work on it). Have you tried downgrading to 0.6.3?

**Comment by palkan** [comment] 2023-03-30 21:03
I pushed a fix to master, could you please check it out?

**Comment by tomchipchase** [comment] 2023-09-08 14:40
@palkan I just faced a similar issue when trying to use [sidekiqswam](https://github.com/sidekiq/sidekiq/wiki/Ent-Multi-Process), we don't have problems using the standard `sidekiq` process.

I can confirm in my case 0.6.3 is fine, and master is fine. Is it possible to get a release with the fix in it so we don't need to revert to an older version?

**Comment by palkan** [comment] 2023-09-12 02:08
@tomchipchase Thanks for confirming that master version works fine. Released in 0.6.6.

**Closed by palkan** 2023-09-12 02:08 UTC
